#ifndef CREDENCIALES_H
#define CREDENCIALES_H

const char* WIFI_SSID = "YOUR_SSID";
const char* WIFI_PASS = "YOUR_WIFI_PASS";

String TELEGRAM_TOKEN = "YOUR_TELEGRAM_TOKEN";
String TELEGRAM_CHAT_ID = "YOUR_TELEGRAM_CHATID";

#endif
